"""
Regression guards for the directional invariants confirmed in SENSITIVITY_REPORT.md
(generated by src/sensitivity_analysis.py). These are the highest-trust-value checks from that
broader diagnostic sweep -- fast, coarse-dt_mins assertions that future changes to
physics_model.py/optimizer.py can't silently flip a sign on. Run: `pytest tests/test_sensitivity.py -v`.

Findings from the full sweep that are NOT encoded here as passing assertions (deliberately):
STOICH_AIR_GAS_RATIO's inertness is a design question, not an invariant to lock in -- see
SENSITIVITY_REPORT.md.
"""

import pytest

from src.physics_model import MelterPhysicsModel
from src.optimizer import HeatingCurveOptimizer

DT_MINS_FAST = 5.0
BASE = dict(
    charged_weight_kg=65000.0, target_duration_hrs=6.0, sp_roof_melt=1150.0, t_switch_hrs=4.0,
    sp_roof_hold=950.0, alloy_name='5052', excess_air_pct=15.0, target_bath_temp_c=720.0,
    dt_mins=DT_MINS_FAST,
)


def _sim(model=None, **overrides):
    opt = HeatingCurveOptimizer(model)
    _, summary = opt.simulate_trajectory(**{**BASE, **overrides})
    return summary


def test_excess_air_increases_gas_and_flue_o2():
    low = _sim(excess_air_pct=10.0)
    high = _sim(excess_air_pct=25.0)
    assert high['cum_gas_nm3'] > low['cum_gas_nm3']
    assert high['flue_o2_pct'] > low['flue_o2_pct']


def test_wall_loss_increases_gas():
    low = _sim(model=MelterPhysicsModel(wall_loss_kw=100.0))
    high = _sim(model=MelterPhysicsModel(wall_loss_kw=500.0))
    assert high['cum_gas_nm3'] > low['cum_gas_nm3']


def test_efficiency_scale_decreases_gas():
    low = _sim(model=MelterPhysicsModel(efficiency_scale=0.8))
    high = _sim(model=MelterPhysicsModel(efficiency_scale=1.6))
    assert high['cum_gas_nm3'] < low['cum_gas_nm3']


def test_burnoff_k0_increases_dross_linearly_ish():
    low = _sim(model=MelterPhysicsModel(burnoff_k0=0.2))
    high = _sim(model=MelterPhysicsModel(burnoff_k0=0.8))
    assert high['cum_dross_kg'] > low['cum_dross_kg']


def test_low_burnoff_ea_dross_is_capped_at_physical_ceiling():
    # Regression guard for the fixed physical-plausibility gap: SENSITIVITY_REPORT.md found
    # burnoff_ea=15000 (well below the calibrated 45000) implied >40% of a 65t charge lost to
    # oxidation in one heat. dross_burnoff_rate_kg_hr() now caps at
    # MAX_PLAUSIBLE_DROSS_RATE_KG_HR, so even an aggressively low Ea must stay under the
    # data-loader-validated 20% plausible yield-loss bound.
    degraded = _sim(model=MelterPhysicsModel(burnoff_ea=15000.0))
    assert degraded['cum_dross_kg'] / BASE['charged_weight_kg'] <= 0.20
    # The calibrated default must be completely unaffected by the ceiling's existence.
    calibrated = _sim()
    assert calibrated['cum_dross_kg'] == pytest.approx(1358.5, rel=0.02)


def test_hearth_area_instance_override_has_full_effect():
    # Regression guard for the fixed bug: radiant_heat_flux_kw() and dross_burnoff_rate_kg_hr()
    # previously read the module-level HEARTH_AREA_M2 global instead of self.HEARTH_AREA_M2, so
    # an instance override only produced ~1/11th the true effect. It must now produce a large,
    # unmistakable swing, not a barely-there one.
    small = MelterPhysicsModel()
    small.HEARTH_AREA_M2 = 30.0
    large = MelterPhysicsModel()
    large.HEARTH_AREA_M2 = 120.0
    gas_small = _sim(model=small)['cum_gas_nm3']
    gas_large = _sim(model=large)['cum_gas_nm3']
    assert gas_large > gas_small
    assert gas_large / gas_small > 1.15, (
        f"HEARTH_AREA_M2 instance override effect too weak (ratio={gas_large / gas_small:.2f}) "
        "-- radiant_heat_flux_kw()/dross_burnoff_rate_kg_hr() may be reading the module-level "
        "constant again instead of self.HEARTH_AREA_M2"
    )


def test_theoretical_energy_respects_instance_gas_lhv():
    # Regression guard for the fixed bug: calculate_theoretical_energy()'s theoretical_gas_nm3
    # previously divided by the module-level GAS_LHV instead of self.GAS_LHV, so an instance
    # override was silently ignored for this (informational) field.
    default_model = MelterPhysicsModel()
    r_default = default_model.calculate_theoretical_energy(65000.0, alloy_name='5052')

    custom_model = MelterPhysicsModel()
    custom_model.GAS_LHV = 50000.0
    r_custom = custom_model.calculate_theoretical_energy(65000.0, alloy_name='5052')

    assert r_custom['theoretical_gas_nm3'] < r_default['theoretical_gas_nm3']
    assert r_custom['theoretical_gas_nm3'] == pytest.approx(
        r_custom['total_energy_kj'] / 50000.0
    )


def test_stoich_air_gas_ratio_not_imported_in_optimizer():
    # Regression guard for the removed dead import: STOICH_AIR_GAS_RATIO was imported into
    # optimizer.py but never referenced there (it's only meaningfully used in data_loader.py's
    # directional excess-air estimate). Confirms it isn't silently reintroduced as an unused
    # import implying it affects the cost/gas model when it doesn't.
    import src.optimizer as optimizer_module
    assert not hasattr(optimizer_module, 'STOICH_AIR_GAS_RATIO')


def test_gas_lhv_increase_decreases_gas_volume():
    # Same energy requirement, fewer Nm3 needed at a higher heating value.
    model = MelterPhysicsModel()
    model.GAS_LHV = 30000.0
    low_lhv = _sim(model=model)
    model2 = MelterPhysicsModel()
    model2.GAS_LHV = 50000.0
    high_lhv = _sim(model=model2)
    assert high_lhv['cum_gas_nm3'] < low_lhv['cum_gas_nm3']


def test_alloy_dross_ordering_matches_mg_content():
    # Ascending Mg content per the manual: pure Al -> 6xxx -> 5052 -> 5083 -> 5182.
    dross = {a: _sim(alloy_name=a)['cum_dross_kg'] for a in ['99.7', '6061', '5052', '5083', '5182']}
    ordered = ['99.7', '6061', '5052', '5083', '5182']
    values = [dross[a] for a in ordered]
    assert values == sorted(values), f"expected monotonic dross ordering, got {dross}"


def test_charged_weight_increases_gas_but_decreases_gas_per_tonne():
    small = _sim(charged_weight_kg=45000.0)
    large = _sim(charged_weight_kg=80000.0)
    assert large['cum_gas_nm3'] > small['cum_gas_nm3']
    small_per_tonne = small['cum_gas_nm3'] / 45.0
    large_per_tonne = large['cum_gas_nm3'] / 80.0
    assert large_per_tonne < small_per_tonne, (
        "gas-per-tonne should fall as charge weight grows (fixed wall_loss_kw amortized over "
        "more mass) -- economies-of-scale regression"
    )


def test_residual_marginal_gas_cost_below_fresh_charge_marginal_cost():
    base = _sim()
    plus_residual = _sim(residual_weight_kg=5000.0)
    plus_charge = _sim(charged_weight_kg=70000.0)
    marginal_residual = (plus_residual['cum_gas_nm3'] - base['cum_gas_nm3']) / 5000.0
    marginal_charge = (plus_charge['cum_gas_nm3'] - base['cum_gas_nm3']) / 5000.0
    assert marginal_residual < marginal_charge


def test_max_roof_sp_limit_never_increases_optimal_cost():
    opt = HeatingCurveOptimizer()
    low_ceiling = opt.optimize_heating_curve(
        65000.0, 6.0, alloy_name='5052', max_roof_sp_limit=1150.0, dt_mins=DT_MINS_FAST,
    )
    high_ceiling = opt.optimize_heating_curve(
        65000.0, 6.0, alloy_name='5052', max_roof_sp_limit=1250.0, dt_mins=DT_MINS_FAST,
    )
    # A wider search space can only tie or improve, never get worse.
    assert high_ceiling['optimal_summary']['total_cost'] <= low_ceiling['optimal_summary']['total_cost'] + 1e-6


def test_short_deadline_becomes_infeasible():
    opt = HeatingCurveOptimizer()
    short = opt.optimize_heating_curve(65000.0, 2.0, alloy_name='5052', dt_mins=DT_MINS_FAST)
    comfortable = opt.optimize_heating_curve(65000.0, 6.0, alloy_name='5052', dt_mins=DT_MINS_FAST)
    assert short['deadline_met'] is False
    assert comfortable['deadline_met'] is True
